In [0]:
import torch
import torch.nn as nn

from torch.nn import functional as F

In [77]:
# 2D卷积
# 输入：[1, 1, 28, 28] -> [1, 3, 26, 26]
# kernel: [3, 1, 3, 3]
x = torch.rand(1, 1, 28, 28)

# torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, 
#        padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')
# Conv2d(input_channel, out_channels, kernel_size, stride, padding)
# kernel_size为kernel的大小，不是个数！ stride=1, padding=0
# input_channel->[b, 1, 28, 28]
# kernel -> [3, 1, 3, 3]
# 输出：[b, 3, 26, 26]
layer = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3, stride=1, padding=0)
out = layer.forward(x)
out.shape

torch.Size([1, 3, 26, 26])

In [78]:
# stride=1, padding=1保持不变
# input_channel->[b, 3, 28, 28]
# kernel -> [3, 3, 3, 3]
# 输出：[b, 3, 28, 28]
layer = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, stride=1, padding=1)
out = layer.forward(out)
out.shape

torch.Size([1, 3, 26, 26])

In [79]:
# stride=2, padding=1
# input_channel->[b, 3, 28, 28]
# kernel -> [3, 3, 3, 3]
# 输出：[b, 3, 28, 28]
layer = nn.Conv2d(3, 3, kernel_size=3, stride=2, padding=1)
out = layer.forward(out)
out.shape

torch.Size([1, 3, 13, 13])

In [81]:
# 推荐直接使用lay()方法，调用魔法函数__call__
# call中实现了写hooks，使用forward无法调用
out = layer(out)
out.size()

torch.Size([1, 3, 7, 7])

In [82]:
layer.weight

Parameter containing:
tensor([[[[-0.0116, -0.0265, -0.0126],
          [ 0.0424, -0.1838,  0.0790],
          [ 0.1784, -0.0730,  0.1868]],

         [[ 0.0121,  0.1530, -0.0381],
          [-0.0709, -0.0588,  0.1355],
          [ 0.0968, -0.0544, -0.0787]],

         [[ 0.1612,  0.1777,  0.1779],
          [ 0.0505, -0.1649,  0.1085],
          [ 0.1866, -0.1748,  0.1522]]],


        [[[-0.0449, -0.1776, -0.1890],
          [ 0.0330,  0.0934, -0.0535],
          [ 0.1747, -0.1811, -0.0057]],

         [[ 0.1759, -0.0510,  0.1369],
          [ 0.0531, -0.1173,  0.0590],
          [-0.0291, -0.1338,  0.1606]],

         [[-0.1117, -0.1067, -0.0381],
          [-0.0743, -0.1620,  0.1536],
          [-0.0341,  0.1597, -0.0300]]],


        [[[ 0.1700, -0.0567, -0.0803],
          [ 0.1524, -0.1152,  0.1462],
          [ 0.0387,  0.1468,  0.1121]],

         [[-0.0468,  0.0562,  0.0776],
          [ 0.1420, -0.0125, -0.0152],
          [-0.1038, -0.0674,  0.0455]],

         [[ 0.1907,  0

In [83]:
layer.weight.shape

torch.Size([3, 3, 3, 3])

In [84]:
layer.bias.shape

torch.Size([3])

In [0]:
# 使用 F.con2d函数
# 小写的是函数，大写的是类

In [0]:
# x:[1, 1, 28, 28]
# w:[16, 3, 5, 5]
# kernel_channel不匹配！

# w = torch.rand(16, 3, 5, 5)
# b = torch.rand(16)
# out = F.conv2d(x, w, b, stride=1, padding=1)

In [87]:
# x:[1, 3, 28, 28]
# w:[16, 3, 5, 5]
# out:[1, 16, 26, 26]
x = torch.randn(1, 3, 28, 28)
out = F.conv2d(x, w, b, stride=1, padding=1)
out.size()

torch.Size([1, 16, 26, 26])

In [88]:
out = F.conv2d(x, w, b, stride=2, padding=2)
out.size()

torch.Size([1, 16, 14, 14])

In [89]:
# 池化层 channel保持不变！
# pooling:下采样
# unsample:上采样
# subsampling:下采样的一种，用来降维，各行采样

# torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, 
# dilation=1, return_indices=False, ceil_mode=False)
x = out
x.shape

torch.Size([1, 16, 14, 14])

In [90]:
# 使用nn.MaxPool2d这个类
layer = nn.MaxPool2d(2, stride=2)
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])

In [91]:
# 使用F.avg_pool2d方法
out = F.avg_pool2d(x, 2, stride=2)
out.shape

torch.Size([1, 16, 7, 7])

In [101]:
x = torch.rand([1, 16, 4, 4])
# 上采样 channel保持不变
# torch.nn.functional.interpolate(input, size=None, 
#               scale_factor=None, mode='nearest', align_corners=None)
out = F.interpolate(x, scale_factor=2, mode='nearest')
out.shape

torch.Size([1, 16, 8, 8])

In [102]:
out = F.interpolate(x, scale_factor=3, mode='nearest')
out.shape

torch.Size([1, 16, 12, 12])

In [108]:
# 使用ReLU函数
# 方法一
layer = nn.ReLU(inplace=True)
out = layer(x)
out.shape

torch.Size([1, 16, 4, 4])

In [106]:
# 方法二
out = F.relu(x)
out.shape

torch.Size([1, 16, 4, 4])

In [109]:
# Batch Normalization
# 好处：1.收敛更快 2.表现更好 3.更健壮（稳定，具有更大的学习速率）
# x ~ U(0, 1)
x = torch.rand(100, 16, 784)
# 输入为channel的个数
layer = nn.BatchNorm1d(16)
out = layer(x)
layer.running_mean

tensor([0.0500, 0.0499, 0.0500, 0.0501, 0.0500, 0.0502, 0.0500, 0.0500, 0.0499,
        0.0501, 0.0500, 0.0502, 0.0499, 0.0501, 0.0501, 0.0501])

In [110]:
layer.running_var

tensor([0.9083, 0.9083, 0.9083, 0.9083, 0.9083, 0.9083, 0.9083, 0.9083, 0.9083,
        0.9083, 0.9083, 0.9083, 0.9084, 0.9084, 0.9084, 0.9083])

In [112]:
# 对二维数据进行BatchNormalization
x = torch.rand([1, 16, 7, 7])
x.shape

torch.Size([1, 16, 7, 7])

In [114]:
layer = nn.BatchNorm2d(16)
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])

In [115]:
# 这里的weight和bias分别对应γ和β，并且需要梯度来进行更新的
layer.weight

Parameter containing:
tensor([0.3315, 0.0591, 0.2944, 0.1770, 0.8691, 0.9482, 0.4884, 0.8218, 0.1969,
        0.6118, 0.1598, 0.6112, 0.1137, 0.1486, 0.3888, 0.0972],
       requires_grad=True)

In [116]:
layer.weight.shape

torch.Size([16])

In [119]:
layer.bias.shape

torch.Size([16])

In [120]:
# 每个channel的μ和方差无法具体体现
# 通过下面的方法可以看出更新中的均值和方差running_main和running_var
# 四个参数形状均为[16]
# affine指定γ和β参数是否需要自动学习
vars(layer)

{'_backend': <torch.nn.backends.thnn.THNNFunctionBackend at 0x7fea3d553668>,
 '_backward_hooks': OrderedDict(),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0472, 0.0461, 0.0531, 0.0465, 0.0536, 0.0457, 0.0419, 0.0489, 0.0539,
                       0.0478, 0.0551, 0.0503, 0.0479, 0.0531, 0.0517, 0.0478])),
              ('running_var',
               tensor([0.9061, 0.9084, 0.9069, 0.9089, 0.9071, 0.9080, 0.9096, 0.9088, 0.9084,
                       0.9073, 0.9072, 0.9086, 0.9084, 0.9073, 0.9064, 0.9077])),
              ('num_batches_tracked', tensor(1))]),
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_modules': OrderedDict(),
 '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([0.3315, 0.0591, 0.2944, 0.1770, 0.8691, 0.9482, 0.4884, 0.8218, 0.1969,
                       0.6118, 0.1598, 0.6112, 0.1137, 0.1486, 0.3888, 0.0972],
                      requ

In [121]:
# 注意：
# BatchNorm和dropout一样，在train和test时是不一样的
# 在test时，均值和方差是全局的。γ和β是不需要更新的。
# 使用下面的模式进行切换
layer.eval()

BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [124]:
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])