In [0]:
import torch
import torch.nn as nn

from torch.nn import functional as F

In [3]:
# 2D卷积
# 输入：[1, 1, 28, 28] -> [1, 3, 26, 26]
# kernel: [3, 1, 3, 3]
x = torch.rand(1, 1, 28, 28)

# torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, 
#        padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')
# Conv2d(input_channel, out_channels, kernel_size, stride, padding)
# kernel_size为kernel的大小，不是个数！ stride=1, padding=0
# input_channel->[b, 1, 28, 28]
# kernel -> [3, 1, 3, 3]
# 输出：[b, 3, 26, 26]
layer = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3, stride=1, padding=0)
out = layer.forward(x)
out.shape

torch.Size([1, 3, 26, 26])

In [4]:
# stride=1, padding=1保持不变
# input_channel->[b, 3, 28, 28]
# kernel -> [3, 3, 3, 3]
# 输出：[b, 3, 28, 28]
layer = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, stride=1, padding=1)
out = layer.forward(out)
out.shape

torch.Size([1, 3, 26, 26])

In [5]:
# stride=2, padding=1
# input_channel->[b, 3, 28, 28]
# kernel -> [3, 3, 3, 3]
# 输出：[b, 3, 28, 28]
layer = nn.Conv2d(3, 3, kernel_size=3, stride=2, padding=1)
out = layer.forward(out)
out.shape

torch.Size([1, 3, 13, 13])

In [6]:
# 推荐直接使用lay()方法，调用魔法函数__call__
# call中实现了写hooks，使用forward无法调用
out = layer(out)
out.size()

torch.Size([1, 3, 7, 7])

In [7]:
layer.weight

Parameter containing:
tensor([[[[-0.1664,  0.1503, -0.0313],
          [ 0.1279,  0.0945,  0.1022],
          [-0.0418,  0.0419,  0.0351]],

         [[ 0.1133,  0.0199, -0.0681],
          [-0.0510,  0.0714,  0.1179],
          [ 0.1075, -0.0284,  0.0665]],

         [[-0.1045,  0.1387,  0.1909],
          [-0.1202, -0.1851, -0.0389],
          [-0.0854, -0.1833,  0.0343]]],


        [[[ 0.0094,  0.0733, -0.1093],
          [ 0.0257,  0.0750,  0.0493],
          [-0.0289,  0.1226,  0.0251]],

         [[-0.1040, -0.0211,  0.0668],
          [ 0.0344, -0.1426, -0.1569],
          [-0.0640,  0.0085, -0.0412]],

         [[-0.0242, -0.0038,  0.0639],
          [ 0.0643,  0.1581, -0.0773],
          [-0.0076,  0.1866,  0.1437]]],


        [[[-0.1165, -0.1432, -0.0828],
          [ 0.1248, -0.1022,  0.0380],
          [-0.0978,  0.1340, -0.1560]],

         [[ 0.1790,  0.1876,  0.1356],
          [ 0.0407,  0.0830, -0.0821],
          [ 0.0150,  0.1333, -0.0331]],

         [[ 0.1794,  0

In [8]:
layer.weight.shape

torch.Size([3, 3, 3, 3])

In [9]:
layer.bias.shape

torch.Size([3])

In [0]:
# 使用 F.con2d函数
# torch.nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
# 小写的是函数，大写的是类
# weight相当于kernel

In [0]:
# x:[1, 1, 28, 28]
# w:[16, 3, 5, 5]
# kernel_channel不匹配！

# x = torch.rand(1, 1, 28, 28)
# w = torch.rand(16, 3, 5, 5)
# b = torch.rand(16)
# out = F.conv2d(x, w, b, stride=1, padding=1)
# out.shape

In [22]:
# x:[1, 3, 28, 28]
# w:[16, 3, 5, 5]
# b:[16]
# out:[1, 16, 26, 26]
x = torch.rand(1, 3, 28, 28)
w = torch.rand(16, 3, 5, 5)
b = torch.rand(16)
out = F.conv2d(x, w, b, stride=1, padding=1)
out.size()

torch.Size([1, 16, 26, 26])

In [23]:
out = F.conv2d(x, w, b, stride=2, padding=2)
out.size()

torch.Size([1, 16, 14, 14])

In [24]:
# 池化层 channel保持不变！
# pooling:下采样
# unsample:上采样
# subsampling:下采样的一种，用来降维，隔行采样

# torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, 
# dilation=1, return_indices=False, ceil_mode=False)
x = out
x.shape

torch.Size([1, 16, 14, 14])

In [0]:
# 使用nn.MaxPool2d这个类
layer = nn.MaxPool2d(2, stride=2)
out = layer(x)
# out = layer.forward(x) 写法不推荐
out.shape

torch.Size([1, 16, 7, 7])

In [0]:
# 使用F.avg_pool2d方法
out = F.avg_pool2d(x, 2, stride=2)
out.shape

torch.Size([1, 16, 7, 7])

In [26]:
x = torch.rand([1, 16, 4, 4])
# 上采样 channel保持不变
# torch.nn.functional.interpolate(input, size=None, 
#               scale_factor=None, mode='nearest', align_corners=None)
out = F.interpolate(x, scale_factor=2, mode='nearest')
out.shape

torch.Size([1, 16, 8, 8])

In [27]:
out = F.interpolate(x, scale_factor=3, mode='nearest')
out.shape

torch.Size([1, 16, 12, 12])

In [29]:
x.shape

torch.Size([1, 16, 4, 4])

In [28]:
# 使用ReLU函数
# 方法一
layer = nn.ReLU(inplace=True)
out = layer(x)
out.shape

torch.Size([1, 16, 4, 4])

In [0]:
# 方法二
out = F.relu(x)
out.shape

torch.Size([1, 16, 4, 4])

In [30]:
# Batch Normalization
# 好处：1.收敛更快 2.表现更好 3.更健壮（稳定，具有更大的学习速率）
# x ~ U(0, 1)
x = torch.rand(100, 16, 784)
# 输入为channel的个数
# (N,C,L)
layer = nn.BatchNorm1d(16)
out = layer(x)
layer.running_mean

tensor([0.0500, 0.0499, 0.0501, 0.0501, 0.0502, 0.0499, 0.0500, 0.0500, 0.0501,
        0.0501, 0.0500, 0.0500, 0.0501, 0.0501, 0.0500, 0.0501])

In [31]:
layer.running_var

tensor([0.9083, 0.9083, 0.9083, 0.9084, 0.9083, 0.9083, 0.9083, 0.9084, 0.9083,
        0.9083, 0.9083, 0.9083, 0.9083, 0.9083, 0.9084, 0.9083])

In [32]:
# 对二维数据进行BatchNormalization
x = torch.rand([1, 16, 7, 7])
x.shape

torch.Size([1, 16, 7, 7])

In [33]:
# (N,C,H,W)
layer = nn.BatchNorm2d(16)
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])

In [34]:
# 这里的weight和bias分别对应γ和β，并且需要梯度来进行更新的
layer.weight

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)

In [35]:
layer.weight.shape

torch.Size([16])

In [36]:
layer.bias.shape

torch.Size([16])

In [37]:
# 每个channel的μ和方差无法具体体现
# 通过下面的方法可以看出更新中的均值和方差running_main和running_var
# 四个参数形状均为[16]
# affine指定γ和β参数是否需要自动学习
vars(layer)

{'_backward_hooks': OrderedDict(),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0506, 0.0453, 0.0527, 0.0533, 0.0495, 0.0527, 0.0380, 0.0435, 0.0428,
                       0.0472, 0.0540, 0.0487, 0.0527, 0.0534, 0.0505, 0.0485])),
              ('running_var',
               tensor([0.9078, 0.9080, 0.9084, 0.9080, 0.9072, 0.9094, 0.9075, 0.9104, 0.9076,
                       0.9085, 0.9084, 0.9084, 0.9084, 0.9115, 0.9085, 0.9070])),
              ('num_batches_tracked', tensor(1))]),
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_modules': OrderedDict(),
 '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)), ('bias', Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requi

In [38]:
# 注意：
# BatchNorm和dropout一样，在train和test时是不一样的
# 在test时，均值和方差是全局的。γ和β是不需要更新的。
# 使用下面的模式进行切换
layer.eval()

BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [39]:
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])