In [1]:
import torch


In [2]:
# 根据内存中的值随机初始化张量
x = torch.empty(3, 5)
print(x)

tensor([[ 1.4013e-45,  4.6566e-10,  0.0000e+00,  0.0000e+00,  7.0065e-45],
        [ 1.1704e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,         nan,         nan, -3.7545e+01]])


In [3]:
# 创建一个随机初始化的张量
x = torch.rand(3, 5)
print(x)

tensor([[0.5820, 0.1317, 0.4861, 0.7133, 0.1090],
        [0.7890, 0.0330, 0.7355, 0.4491, 0.4918],
        [0.7409, 0.4517, 0.0105, 0.9088, 0.1563]])


In [4]:
# 创建一个初始值为0的张量
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 直接通过数值创建张量
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 根据存在的张量创建张量
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4257,  1.0956,  0.2981],
        [-1.8625, -0.2728,  0.0756],
        [-1.8514, -1.1368, -2.1286],
        [-1.4463, -0.9376,  0.1773],
        [-1.3330,  0.0303, -0.6451]])


In [7]:
x.size()
y = torch.rand(5, 3)
x+y

tensor([[ 0.8294,  1.3463,  0.8594],
        [-1.0234,  0.4671,  0.6366],
        [-1.6013, -0.4286, -1.3716],
        [-0.7241, -0.2178,  0.7523],
        [-1.2918,  0.0918,  0.1216]])

In [8]:
print(torch.add(x, y))

tensor([[ 0.8294,  1.3463,  0.8594],
        [-1.0234,  0.4671,  0.6366],
        [-1.6013, -0.4286, -1.3716],
        [-0.7241, -0.2178,  0.7523],
        [-1.2918,  0.0918,  0.1216]])


In [9]:
# 也可以提供一个输出张量作为参数
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8294,  1.3463,  0.8594],
        [-1.0234,  0.4671,  0.6366],
        [-1.6013, -0.4286, -1.3716],
        [-0.7241, -0.2178,  0.7523],
        [-1.2918,  0.0918,  0.1216]])


In [10]:
# adds x to y
y.add_(x)
print(y)
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.

tensor([[ 0.8294,  1.3463,  0.8594],
        [-1.0234,  0.4671,  0.6366],
        [-1.6013, -0.4286, -1.3716],
        [-0.7241, -0.2178,  0.7523],
        [-1.2918,  0.0918,  0.1216]])


In [11]:
# 可以使用numpy的切片方法
print(x[:, 1])

tensor([ 1.0956, -0.2728, -1.1368, -0.9376,  0.0303])


In [12]:
# Resize Tensor
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
# If you have a one element tensor, 
# use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.4386])
-1.4385603666305542


In [14]:
# The Torch Tensor and NumPy array will share their underlying memory locations 
# (if the Torch Tensor is on CPU), 
# and changing one will change the other.
a = torch.ones(5)
print(a)


tensor([1., 1., 1., 1., 1.])


In [15]:
# tensor -> numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
import numpy as np
a = np.ones(5)
# numpy -> tenor
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_avaliable():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
